@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.ssblur.scriptor.integration.recipes;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;