name: publish

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    environment: publish
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - id: changelog
        uses: ssblur/git-changelog-action@v1
      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'
      - name: Sync Body
        run: bash ./gradlew fabric:modrinthSyncBody
        env:
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
      - name: Publish Forge
        run: bash ./gradlew forge:modrinth
        env:
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
          CHANGELOG: ${{ steps.changelog.outputs.changelog }}
          JAR_SIGNING_STORE: ${{ secrets.JAR_SIGNING_STORE }}
          JAR_SIGNING_ALIAS: ${{ secrets.JAR_SIGNING_ALIAS }}
          JAR_SIGNING_STORE_PASS: ${{ secrets.JAR_SIGNING_STORE_PASS }}
          JAR_SIGNING_KEY_PASS: ${{ secrets.JAR_SIGNING_KEY_PASS }}
      - name: Publish Fabric
        run: bash ./gradlew fabric:modrinth
        env:
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
          CHANGELOG: ${{ steps.changelog.outputs.changelog }}
          JAR_SIGNING_STORE: ${{ secrets.JAR_SIGNING_STORE }}
          JAR_SIGNING_ALIAS: ${{ secrets.JAR_SIGNING_ALIAS }}
          JAR_SIGNING_STORE_PASS: ${{ secrets.JAR_SIGNING_STORE_PASS }}
          JAR_SIGNING_KEY_PASS: ${{ secrets.JAR_SIGNING_KEY_PASS }}

